package main

import (
	"encoding/json"
	"evm-scanner/token"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"sort"
	"text/template"
	"time"
)

const URL = "https://chainlist.org/rpcs.json"
const OUTPUT = "token/native.go"

type ChainInfo struct {
	ChainID        uint64     `json:"chainId"`
	Name           string     `json:"name"`
	Chain          string     `json:"chain"`
	IsTestnet      bool       `json:"isTestnet"`
	NativeCurrency token.Info `json:"nativeCurrency"`
}

type ChainList []ChainInfo

func main() {
	// 从 URL 获取信息
	resp, err := http.Get(URL)
	if err != nil {
		fmt.Printf("获取链信息失败: %v\n", err)
		os.Exit(1)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		fmt.Printf("HTTP 请求失败，状态码: %d\n", resp.StatusCode)
		os.Exit(1)
	}

	// 读取响应体
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		fmt.Printf("读取响应失败: %v\n", err)
		os.Exit(1)
	}

	// 解析 JSON
	var chains ChainList
	err = json.Unmarshal(body, &chains)
	if err != nil {
		fmt.Printf("解析 JSON 失败: %v\n", err)
		os.Exit(1)
	}

	// 过滤掉测试网并按 ChainID 排序
	mainnetChains := append(ChainList(nil), chains...)

	sort.Slice(mainnetChains, func(i, j int) bool {
		return mainnetChains[i].ChainID < mainnetChains[j].ChainID
	})

	// 生成 Go 文件
	err = generateGoFile(mainnetChains)
	if err != nil {
		fmt.Printf("生成 Go 文件失败: %v\n", err)
		os.Exit(1)
	}

	// 格式化 Go 文件
	err = exec.Command("gofmt", "-w", OUTPUT).Run()
	if err != nil {
		fmt.Printf("格式化 Go 文件失败: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("成功生成 %s，共 %d 条货币信息\n", OUTPUT, len(mainnetChains))
}

func generateGoFile(chains ChainList) error {
	// 准备模板
	tmpl := `// Code generated by gen-native-currencys.go. DO NOT EDIT.
// Source: {{.URL}}
// Date: {{.Date}}

package token

var NativeCurrencys = map[uint64]*Info{
{{- range .Chains}}
	{{.ChainID}}: {"{{.NativeCurrency.Symbol}}", {{.NativeCurrency.Decimals}}, "{{.NativeCurrency.Name}}"},
{{- end}}
}
`

	// 解析模板
	t, err := template.New("chains").Parse(tmpl)
	if err != nil {
		return err
	}

	// 创建输出文件
	outputPath := OUTPUT

	file, err := os.Create(outputPath)
	if err != nil {
		return err
	}
	defer file.Close()
	now := time.Now()

	// 执行模板
	data := map[string]any{
		"URL":    URL,
		"Chains": chains,
		"Date":   now.Format("2006-01-02 15:04:05"),
	}

	return t.Execute(file, data)
}
